name: Build & Zip
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install compiler
        run: |
          sudo apt update
          sudo apt install -y mingw-w64 zip

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install nuitka

      # 1. 超快文件夹打包
      - name: Build with Nuitka
        run: |
          python -m nuitka \
            --standalone \
            --mingw64 \
            main.py

      # 2. 自动把文件夹打成 ZIP！！！
      - name: Zip output folder
        run: zip -r build.zip main.dist/

      # 3. 只上传这一个 ZIP
      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build.zip
